image: Ubuntu  # ����� ��� ������

stack: jdk 11  # ������ JDK

branches:
  only:
    - master  # ����� git

build: off  # ����� ������������ ���� ������ ������

install:
  # ��������� SUT (& ��������, ��� � ������� ������ - �� ��������� �������� ��� ������� ������)
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info  # ��������� ����, ���� --info ��������� �������� ������ ����������